name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
          # 登录阿里云镜像仓库
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
          # 使用Dockerfile构建镜像
          docker build . --file docker_example/Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/junweny/langflow:1.0.0
          # 推送镜像到镜像仓库
          docker push registry.cn-hangzhou.aliyuncs.com/junweny/langflow:1.0.0
